### PR TITLE
Fix storeSystemData 

### LINKED ISSUE #685: Fix storeSystemData

### PR DESCRIPTION
**Pull request by stefanvit**
## Description
Fix storeSystemData 

**Resolves #685 

## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: core/apis.go [hunk 1]
```diff
@@ -81,7 +81,20 @@ func (c *APIs) GetServiceID() string {
...
+	}
+	// if it doesn't exist create one
+	if col != true {
+		err := c.app.storage.CreateAuthTypesCollection()
+		if err != nil {
+			return err
+		}
+	}
 
+	fmt.Print(col)
```
Comment (petyos) [inline core/apis.go:97]: Do not use fmt for printing but you should use the logger field in the struct.

File: core/apis.go [hunk 2]
```diff
@@ -81,7 +81,20 @@ func (c *APIs) GetServiceID() string {
 
 func (c *APIs) storeSystemData() error {
 	newDocuments := make(map[string]string)
+	//check if auth_types collection exists
+	col, err := c.app.storage.CheckAuthTypesExists()
+	if err != nil {
+		return err
+	}
+	// if it doesn't exist create one
+	if col != true {
```
Comment (petyos) [inline core/apis.go:90]: The construction if col {} is shorter.

File: core/interfaces.go [hunk 3]
```diff
@@ -262,6 +262,9 @@ type Storage interface {
 	UpdateApplicationOrganization(context storage.TransactionContext, applicationOrganization model.ApplicationOrganization) error
 
 	InsertAPIKey(context storage.TransactionContext, apiKey model.APIKey) (*model.APIKey, error)
+
+	CheckAuthTypesExists() (bool, error)
```
Comment (petyos) [inline core/interfaces.go:266]: Let's make these 2 functions to be generic, i.e. it should have a parameter collectionName.

File: driven/storage/adapter.go [hunk 4]
```diff
@@ -4231,6 +4232,57 @@ func (sa *Adapter) DeleteDevice(context TransactionContext, id string) error {
...
+	client := sa.db.dbClient
+	dbName := sa.db.mongoDBName
+	collectionName := "auth_types"
+
+	opts := options.FindOne()
+
+	database := client.Database(dbName)
+	collections, err := database.ListCollectionNames(nil, opts)
+	if err != nil {
+		log.Fatal(err)
```
Comment (petyos) [inline driven/storage/adapter.go:4247]: Do not crash the service if error here. You just need to return it.

File: driven/storage/adapter.go [hunk 5]
```diff
@@ -4231,6 +4232,57 @@ func (sa *Adapter) DeleteDevice(context TransactionContext, id string) error {
...
+
+	collectionExists := false
+	for _, coll := range collections {
+		if coll == collectionName {
+			collectionExists = true
+			break
+		}
+	}
+	if collectionExists {
+		fmt.Printf("The collection '%s' exists.\n", collectionName)
```
Comment (petyos) [inline driven/storage/adapter.go:4258]: Do not use fmt for printing but you should use the logger field in the struct.

File: driven/storage/adapter.go [hunk 6]
```diff
@@ -4231,6 +4232,57 @@ func (sa *Adapter) DeleteDevice(context TransactionContext, id string) error {
...
+
+	// Creating a collection
+	collection := database.Collection(collectionName)
+	_, err := collection.InsertOne(nil, collection)
+	if err != nil {
+		return err
+	}
+	// You can perform additional configuration or operations on the collection if needed
+
+	fmt.Printf("Collection %s created in database %s\n", collectionName, dbName)
```
Comment (petyos) [inline driven/storage/adapter.go:4282]: Do not use fmt for printing but you should use the logger field in the struct.

**Review by petyos — CHANGES_REQUESTED** [review]
