### PR TITLE
[#506] Authorization policy comments not working

### LINKED ISSUE #506: [BUG] Authorization policy comments not working
**Describe the bug**
The comments we added to the authorization policies are not working as expected. They are not being ignored and are having an impact on authorization.

**To Reproduce**
If i have this(without comments):
_p, get_content-items, /content/admin/content_items, (GET)_ 
and hit GET  /content/admin/content_items then it works and give response 200

but if I have this(with comments):
_p, get_content-items, /content/admin/content_items, (GET) #Any comment_
then it gives Forbidden. 

Also sometimes it allows to have a comment, for example this:
_p, all_content-items, /content/admin/content_items, (GET)|(POST)|(DELETE)|(PUT) #All content items actions_
works as expected.

**Expected behavior**
We expect comments to be ignored and have no impact on the authorization. We should update to the latest version of the auth library after https://github.com/rokwire/core-auth-library-go/issues/57 is released and update our authorization policies appropriately to resolve this issue.

### PR DESCRIPTION
**Pull request by shurwit**
## Description
_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._
Update auth library and fix authorization policies to use new comment format.

**Resolves #506**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by shurwit** [comment]
Hi @petyos, please take a look at this when you get a chance. I have updated to the latest version of the auth library. This new auth library version is a large update with many breaking changes which you can see here: https://github.com/rokwire/core-auth-library-go/releases/tag/v2.0.1. 

In the release notes above (also in the README in the auth library) are some notes about the new "comment" system. Essentially I just added a new column to the authorization model that is ignored when checking the policies. This means that every permission policy CSV must now have one more comma at the end even if no comment is provided. 

Let me know if you have any questions or comments about these changes. Thanks!

File: core/auth/auth.go [hunk 1]
```diff
@@ -2383,8 +2391,8 @@ func (l *LocalDataLoaderImpl) LoadServices() ([]authservice.ServiceReg, error) {
 	return authRegs, nil
 }
 
-//NewLocalDataLoader creates and configures a new LocalDataLoaderImpl instance
-func NewLocalDataLoader(storage Storage) *LocalDataLoaderImpl {
+//NewLocalServiceRegLoader creates and configures a new LocalServiceRegLoaderImpl instance
+func NewLocalServiceRegLoader(storage Storage) *LocalDataLoaderImpl {
```
Comment (roberlander2) [inline core/auth/auth.go:2395]: We can delete the `GetAccessToken` and `GetDeletedAccounts` functions here, since they are not part of the `ServiceRegLoader` interface. I think we should update the name of `LocalDataLoaderImpl` for consistency as well.

File: core/auth/auth.go [hunk 2]
```diff
@@ -149,16 +150,23 @@ func NewAuth(serviceID string, host string, authPrivKey *rsa.PrivateKey, storage
...
+	}
+
+	serviceRegLoader := NewLocalServiceRegLoader(storage)
 
-	authService, err := authservice.NewAuthService(serviceID, host, dataLoader)
+	// Instantiate a ServiceRegManager to manage the service registration data loaded by serviceRegLoader
+	serviceRegManager, err := authservice.NewServiceRegManager(&authService, serviceRegLoader)
 	if err != nil {
-		return nil, errors.WrapErrorAction(logutils.ActionInitialize, "auth service", nil, err)
+		log.Fatalf("Error initializing service registration manager: %v", err)
```
Comment (roberlander2) [inline core/auth/auth.go:164]: Is there a reason we need to use the `log` package instead of `auth.logger` to do this?

File: core/auth/auth.go [hunk 3]
```diff
@@ -22,17 +22,18 @@ import (
...
 	"time"
 
 	"github.com/golang-jwt/jwt"
 	"github.com/google/uuid"
-	"github.com/rokwire/core-auth-library-go/authorization"
-	"github.com/rokwire/core-auth-library-go/authservice"
-	"github.com/rokwire/core-auth-library-go/authutils"
-	"github.com/rokwire/core-auth-library-go/sigauth"
-	"github.com/rokwire/core-auth-library-go/tokenauth"
+	"github.com/rokwire/core-auth-library-go/v2/authorization"
```
Comment (roberlander2) [inline core/auth/auth.go:32]: With the upgrade to v2 of the auth library, we should update the service account system to use the `"all"` string instead of `nil`. Below are the two commits in #354 that make these changes. The second link shows the final state after the changes, and the first link shows some intermediate changes that may help make the second set of changes clearer.

- https://github.com/rokwire/core-building-block/pull/354/commits/396792b014d0a499b1aa5a32f2839a203bd3165c
- https://github.com/rokwire/core-building-block/pull/354/commits/0565ff975566841c8373b8cd71ecdd93983b9bbc

**Review by roberlander2 — CHANGES_REQUESTED** [review]
Thanks @shurwit, this looks good so far. I left a few comments below.

**Comment by shurwit** [comment]
Thanks for the feedback @roberlander2! I have fixed the issues you pointed out. Please take a look and let me know if you see anything else when you get a chance. Thanks again!

**Review by roberlander2 — DISMISSED** [review]
Thanks @shurwit, LGTM.
